"""Note about new changes

Revision ID: 3550ef47aa3c
Revises: e114db6f53fc
Create Date: 2025-10-27 19:11:44.415741

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3550ef47aa3c"
down_revision = "e114db6f53fc"
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    pass


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('user',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('username', sa.String(length=80), nullable=False),
#     sa.Column('password_hash', sa.String(length=200), nullable=False),
#     sa.PrimaryKeyConstraint('id'),
#     sa.UniqueConstraint('username')
#     )
#     op.create_table('budget',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('user_id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(length=100), nullable=False),
#     sa.Column('month_duration', sa.Integer(), nullable=False),
#     sa.Column('gross_income', sa.Numeric(precision=11, scale=2), nullable=False),
#     sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('budget_item',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('budget_id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(length=50), nullable=False),
#     sa.Column('category', sa.String(length=30), nullable=False),
#     sa.Column('total', sa.Numeric(precision=11, scale=2), nullable=False),
#     sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('budget_item')
#     op.drop_table('budget')
#     op.drop_table('user')
#     # ### end Alembic commands ###
