"""Add unique constraint for user_id and name in Budget

Revision ID: e1c5361166b5
Revises: 3550ef47aa3c
Create Date: 2025-10-28 17:00:26.073501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c5361166b5'
down_revision = '3550ef47aa3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_budget_name_per_user', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint('unique_budget_name_per_user', type_='unique')

    # ### end Alembic commands ###
